### ISSUE TITLE
Decide on and build plot methods

### ISSUE THREAD

**Issue by ellisp** [ellisp/forecastHybrid#1]

**Comment by dashaub** [comment]
Any ideas for plotting our ensemble object?
For the individual component models we can use the individual plot methods from the "forecast" package for each model. For example, `plot(hybridModel(wineind, models = "aten"))` could be setup to create a 2x2 plot by `par(mfrow = c(2, 2))` and then plot the Arima/tbats/ets/nnetar objects using the forecast package's methods. The nnetar object does not have a plot method, so that will need to be excluded, and the `plot.Arima()` method already sets `par(mfrow = c(1, 2))`, so this approach might need some work.
If we want to plot both the individual component models and something for the ensemble we could put in a "Hit \<Return\> to see the next plot:" prompt like in the `plot.lm()` method

**Comment by dashaub** [comment]
Basic--fairly horrific--plotting is implemented here: 657c5b83a967f59ee0668ffaffbe3e9f6bb01f84
It merely plots the original series and the fitted values. The idea of plotting each of the models by setting `mfrow` won't work because some of the individual models themselves change this in their own plot methods. Upon reflection, the "Hit <Return> to see the next plot:" behavior of `plot.lm()` is an anomaly and shouldn't be emulated. We could just splatter all of the individual model plots one after another.

**Comment by dashaub** [comment]
This second behavior is implemented here with `type = "models"`: 241e002e28b08070eda16533cb5d5af774650f26
We can add ggplot support and other plot types later, especially once the forecast package itself implemented ggplot.
