### ISSUE TITLE
 fpp not explicitly imported

### ISSUE THREAD

**Issue by ellisp** [ellisp/forecastHybrid#15]
currently the build checks report a problem with {fpp} being listed as a dependency but never being imported.  I'm presuming we're likely to use it for example data; so I'm just logging an issue so we remember to explicitly import either the whole namespace or just an explicit dataset when we get to that point.

**Comment by dashaub** [comment]
`fpp` is nice for building unit tests since you have series with different behaviors (frequency of 4, 12, etc). I'm importing `fpp` now with roxygen2, but I think you're right that we should ultimately just import the datasets that we need: no need to clutter the namespace more than necessary.
Fixed for now in 88b89d491629c6f6a29d64c0ec22c55b854ad6de
