### ISSUE TITLE
Add in prediction intervals to forecast.hybridModel

### ISSUE THREAD

**Issue by ellisp** [ellisp/forecastHybrid#2]

**Comment by dashaub** [comment]
There are lots of ways to do this. We might want to allow multiple methods here the same way we would allow multiple weighting methods for the errors (e.g. "equal", "insample.errors", "cv.errors").
For this I can immediately think of "extreme" (i.e. the highest/lowest prediction interval for an individual forecast) and "mean" (i.e. average of the upper/lower limits from all methods), "weighted" (using the same model weights of the ensemble for the lower/upper limits), and "cv" (upper/lower limits created for the ensemble by finding the standard error for each forecast horizon by running cv on the series). We might want to start with the easiest "extreme" and "mean" methods first. Since nnetar objects don't create prediction intervals we'll have to exclude them. The averaging method _might_  unfortunately produce lower/upper limits above/below the mean forecast point, respectively, depending on the weights of the ensemble.

**Comment by dashaub** [comment]
The good news: A rudimentary implementation for prediction intervals (with two levels) works. So this now plots successfully `plot(forecast(hybridModel(wineind), level = c(80, 95), h = 216))`
The bad news: This uses only the max for the upper limit and the min for the lower limit, so it is overly conservative. Furthermore, the implementation is bad and only works with two levels. It will need to be redone, but we have some basic functionality for now.

**Comment by dashaub** [comment]
This is fully fixed here:
77a261c9d3a5bd27a1909ae36b2c6fc2801b9b5b

We'll still should think about methods for combining the prediction intervals, but those are enhancements.
