### ISSUE TITLE
automated model selection

### ISSUE THREAD

**Issue by ellisp** [ellisp/forecastHybrid#4]
choose the best combination of contributing models

**Comment by dashaub** [comment]
We could do this in a way similar to `auto.arima()`, i.e. build a wrapper model (say, `auto.hybridModel()`) that calls `hybridModel()` with various combinations of aenst arguments. Once we get all the various weights/error methods worked out, we can allow the user to select the best model based on the selected insample/cv error. So long as we don't add tons of new models we could search all possible combinations of aenst models since they run _reasonably_ fast, but we might give an argument to control whether an exhaustive search should be included or not. We might want to check out the memoise package for this since we would be running the same individual auto.arima/ets/nnetar/stlm/tbats calls many times.

**Comment by ellisp** [comment]
I like the idea of a new wrapper `auto.hybridModel()` rather than somehow building this into the main function.

**Comment by ellisp** [comment]
I think I'll close this off because I don't think it has anything to add to choosing the weights via cross validation, which is now already implemented.
