### ISSUE TITLE
add unit tests

### ISSUE THREAD

**Issue by dashaub** [ellisp/forecastHybrid#6]
Add unit tests to enforce behavior between versions and add stringency during package building. Travis continuous integration would be nice.

**Comment by ellisp** [comment]
I've added in Travis CI but I'm not entirely happy with it as it is.  Because I've set this up with the package in a subdirectory of the repository root this seems to be a non-standard setup and I've had to do a lot of mucking about with this setup to get it to work - and I'm not entirely sure I have... for instance, the CRAN check has 3 warnings and a note which I think should count as a fail but it still shows up as a successful build.  I'll continue to investigate.  We should make liberal use of checks on our own machines though!

**Comment by dashaub** [comment]
A few builds broke (but it is fixed now) so it is in fact working. We should definitely fix the warnings/notes. One more item for the wish list:
https://coveralls.io/sign-up
